config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users

  resources :links do
    member do
      put 'like',    to: 'links#upvote'
      put 'dislike', to: 'links#downvote'
    end
    resources :comments
  end

  root 'links#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @links = Link.all
  end

  def show
  end

  def new
    @link = current_user.links.build
  end

  def edit
  end

  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  private

    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.slim
= div_for(comment) do
  .comments_wrapper.clearfix
    .pull-left
      p.lead= comment.body
      p
        small
          | Submitted
          strong
            |  #{time_ago_in_words(comment.created_at)}
            |   ago
          |   by #{comment.user.name}
    .btn-group.pull-right
      - if comment.user == current_user
        = link_to 'Destroy', comment, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-default"

app/views/comments/_form.html.slim
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :link_id
    = f.number_field :link_id
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th Link
      th Body
      th User
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.link_id
        td = comment.body
        td = comment.user
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Link:
  = @comment.link_id
p
  strong Body:
  = @comment.body
p
  strong User:
  = @comment.user

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Link Notes
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header.navbar.navbar-default role='navigation'
      .navbar-inner
        .container
          #logo.navbar-brand= link_to 'Link Notes', root_path
          nav.collapse.navbar-collapse.navbar-ex1-collapse
            - if user_signed_in?
              ul.nav.navbar-nav.navbar-right
                li= link_to 'New link', new_link_path
                li= link_to 'Account', edit_user_registration_path
                li= link_to 'Sign out', destroy_user_session_path, :method => :delete
            - else
              ul.nav.navbar-nav.pull-right
                li= link_to 'Sign up', new_user_registration_path
                li= link_to 'Sign in', new_user_session_path
    #main_content.container
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert alert-#{name}")
      #content.col-md-9.center-block
        = yield

app/views/links/_form.html.slim
= form_for(@link) do |f|
  - if @link.errors.any?
    #error_explanation
      h2
        = pluralize(@link.errors.count, 'error')
        |  prohibited this link from being saved:
      ul
        - @link.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :title
    br
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :url
    br
    = f.text_field :url, class: 'form-control'
  .form-group
    = f.submit 'Submit', class: 'btn btn-lg btn-primary'

app/views/links/edit.html.slim
h1
  | Editing Link
= render 'form'
= link_to 'Show', @link
|  | 
= link_to 'Back', links_path

app/views/links/index.html.slim
- @links.each do |link|
  .link.row.clearfix
    h2
      = link_to link.title, link
      br
      small.author
        | Submitted #{time_ago_in_words(link.created_at)} by #{link.user.name}
    .btn-group
      a.btn.btn-primary.btn-sm href="#{link.url}"  Visit Link
    .btn-group
      = link_to like_link_path(link), method: :put, class: 'btn btn-default btn-sm' do
        span.glyphicon.glyphicon-chevron-up
        |   Upvote #{link.get_upvotes.size}
      = link_to dislike_link_path(link), method: :put, class: 'btn btn-default btn-sm' do
        span.glyphicon.glyphicon-chevron-down
        |   Downvote #{link.get_downvotes.size}

app/views/links/new.html.slim
h1
  | New Link
= render 'form'
= link_to 'Back', links_path

app/views/links/show.html.slim
.page-header
  h1
    a href="#{@link.url}" = @link.title
    br
    small
      | Submitted by #{@link.user.name}

.btn-group.pull-right
  = link_to like_link_path(@link), method: :put, class: 'btn btn-default btn-sm' do
    span.glyphicon.glyphicon-chevron-up
    |   Upvote #{@link.get_upvotes.size}
  = link_to dislike_link_path(@link), method: :put, class: 'btn btn-default btn-sm' do
    span.glyphicon.glyphicon-chevron-down
    |   Downvote #{@link.get_downvotes.size}

.btn-group
  = link_to 'Visit URL', @link.url, class: 'btn btn-primary'
- if @link.user == current_user
  .btn-group
    = link_to 'Edit', edit_link_path(@link), class: 'btn btn-default'
    = link_to 'Destroy', @link, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default'

h3.comments_title
  = @link.comments.count
  |   Comments
#comments
  = render :partial => @link.comments
  = simple_form_for [@link, Comment.new]  do |f|
    .field
      = f.text_area :body, class: 'form-control'
    br
      = f.submit 'Add Comment', class: 'btn btn-primary'